"""
PromptBuilder — Layer 2 component of the Helix AI Cascading Pipeline.

Responsible for assembling the final prompt that is sent to the fine-tuned
Qwen model.  It combines:
  1. The system instruction (role definition)
  2. The execution plan from the Planner agent
  3. Few-shot examples retrieved by the Search Agent from the knowledge base
  4. The raw legacy source code

This keeps prompt engineering logic isolated from the ML inference logic
inside ml_reasoner.py.
"""

from typing import Any, Dict, List, Optional


# ── Base templates ──────────────────────────────────────────────────────────

SYSTEM_INSTRUCTION = (
    "You are Helix AI, a legacy Python modernization model.\n"
    "Convert old Python code to current Python while preserving behavior.\n"
    "Return only the final migrated code.\n"
)

FEW_SHOT_BLOCK = """Here are {count} examples of successful past migrations:

{examples}
"""

SINGLE_EXAMPLE = """--- Example {index} ({pattern_id}) ---
### Input:
{input_code}
### Output:
{output_code}
"""

PLAN_BLOCK = """The following transformation plan has been generated by the analysis pipeline:
{plan_summary}
Apply these transformations to the code below.
"""

INPUT_BLOCK = """### Instruction:
Modernize this legacy Python code to current Python while preserving behavior.

### Input:
{input_code}

### Response:
"""


class PromptBuilder:
    """Assembles structured prompts for the ML inference engine."""

    def build(
        self,
        code: str,
        few_shot_examples: Optional[List[Dict[str, Any]]] = None,
        plan: Optional[Dict[str, Any]] = None,
    ) -> str:
        """Build the full prompt string.

        Parameters
        ----------
        code : str
            The raw legacy Python source code to modernize.
        few_shot_examples : list[dict], optional
            Records returned by ``SearchAgent.process()``.  Each dict must
            contain ``pattern_id``, ``input_code``, and ``output_code``.
        plan : dict, optional
            The execution plan dict returned by ``PlannerAgent.process()``.
            If provided, a plan summary section is prepended.

        Returns
        -------
        str
            A fully assembled prompt ready for tokenisation.
        """
        sections: List[str] = [SYSTEM_INSTRUCTION]

        # ── Few-shot RAG section ────────────────────────────────────────
        if few_shot_examples:
            rendered = []
            for idx, ex in enumerate(few_shot_examples, 1):
                rendered.append(
                    SINGLE_EXAMPLE.format(
                        index=idx,
                        pattern_id=ex.get("pattern_id", "unknown"),
                        input_code=ex.get("input_code", ""),
                        output_code=ex.get("output_code", ""),
                    )
                )
            sections.append(
                FEW_SHOT_BLOCK.format(
                    count=len(few_shot_examples),
                    examples="\n".join(rendered),
                )
            )

        # ── Plan section (from Planner agent) ───────────────────────────
        if plan:
            selected = plan.get("selected_plans", [])
            if selected:
                lines = []
                for i, p in enumerate(selected, 1):
                    sug = p.get("suggestion", {})
                    lines.append(
                        f"  {i}. [{sug.get('type', '?')}] "
                        f"{sug.get('target', '?')} → {sug.get('suggestion', '?')} "
                        f"(confidence {sug.get('confidence', 0):.0%})"
                    )
                sections.append(
                    PLAN_BLOCK.format(plan_summary="\n".join(lines))
                )

        # ── Input code section ──────────────────────────────────────────
        sections.append(INPUT_BLOCK.format(input_code=code))

        return "\n".join(sections)
